# Global settings applied to all models unless overridden
[*]

[llama32]
model = models/llama32-3b-q4km.gguf
ctx-size = 16384

[ministral3]
model = models/Ministral-3-3B-q4km.gguf
ctx-size = 16384

[qwen-3.5-4b]
model = models/qwen3.5-4b-q4km.gguf
ctx-size = 16384

[qwen-3.5-2b]
model = models/qwen3.5-2b-q4km.gguf

[qwen-2.5-3b]
model = models/qwen2.5-coder-3b-q4km.gguf
